<?xml version="1.0" encoding="utf-8"?><Database Name="pizzani1_subscribe" Class="PizzaNightDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mi3-wsq3.a2hosting.com;Initial Catalog=pizzani1_subscribe;Persist Security Info=True;User ID=pizzani1_kidrobo" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="pizzani1_subscribeConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="pizzani1_kidrobo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Salt" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>